using KumikoUI.Core.Models;

namespace KumikoUI.Core.Tests;

public class DataGridColumnTests
{
    // ── Defaults ──────────────────────────────────────────────────

    [Fact]
    public void DefaultValues_AreReasonable()
    {
        var col = new DataGridColumn();
        Assert.Equal(string.Empty, col.Header);
        Assert.Equal(string.Empty, col.PropertyName);
        Assert.Equal(DataGridColumnType.Text, col.ColumnType);
        Assert.Equal(120f, col.Width);
        Assert.Equal(40f, col.MinWidth);
        Assert.Equal(float.MaxValue, col.MaxWidth);
        Assert.Equal(ColumnSizeMode.Fixed, col.SizeMode);
        Assert.Equal(1f, col.StarWeight);
        Assert.True(col.IsVisible);
        Assert.False(col.IsReadOnly);
        Assert.True(col.AllowTabStop);
        Assert.True(col.AllowSorting);
        Assert.True(col.AllowResize);
        Assert.True(col.AllowReorder);
        Assert.True(col.AllowFiltering);
        Assert.Equal(SortDirection.None, col.SortDirection);
        Assert.Equal(0, col.SortOrder);
        Assert.Equal(ColumnFreezeMode.None, col.FreezeMode);
        Assert.Null(col.ActiveFilter);
    }

    [Fact]
    public void Id_AutoGenerated_IsNotEmpty()
    {
        var col = new DataGridColumn();
        Assert.False(string.IsNullOrWhiteSpace(col.Id));
    }

    [Fact]
    public void Id_TwoColumns_HaveDifferentIds()
    {
        var col1 = new DataGridColumn();
        var col2 = new DataGridColumn();
        Assert.NotEqual(col1.Id, col2.Id);
    }

    // ── IsFrozen / FreezeMode ─────────────────────────────────────

    [Fact]
    public void IsFrozen_SetTrue_SetsFreezeModeToLeft()
    {
        var col = new DataGridColumn();
        col.IsFrozen = true;
        Assert.Equal(ColumnFreezeMode.Left, col.FreezeMode);
    }

    [Fact]
    public void IsFrozen_SetFalse_SetsFreezeModeToNone()
    {
        var col = new DataGridColumn { FreezeMode = ColumnFreezeMode.Left };
        col.IsFrozen = false;
        Assert.Equal(ColumnFreezeMode.None, col.FreezeMode);
    }

    [Fact]
    public void IsFrozen_GetTrue_WhenFreezeModeIsLeft()
    {
        var col = new DataGridColumn { FreezeMode = ColumnFreezeMode.Left };
        Assert.True(col.IsFrozen);
    }

    [Fact]
    public void IsFrozen_GetFalse_WhenFreezeModeIsRight()
    {
        var col = new DataGridColumn { FreezeMode = ColumnFreezeMode.Right };
        Assert.False(col.IsFrozen);
    }

    [Fact]
    public void IsFrozenRight_SetTrue_SetsFreezeModeToRight()
    {
        var col = new DataGridColumn();
        col.IsFrozenRight = true;
        Assert.Equal(ColumnFreezeMode.Right, col.FreezeMode);
    }

    [Fact]
    public void IsFrozenRight_SetFalse_SetsFreezeModeToNone()
    {
        var col = new DataGridColumn { FreezeMode = ColumnFreezeMode.Right };
        col.IsFrozenRight = false;
        Assert.Equal(ColumnFreezeMode.None, col.FreezeMode);
    }

    [Fact]
    public void IsFrozenRight_GetTrue_WhenFreezeModeIsRight()
    {
        var col = new DataGridColumn { FreezeMode = ColumnFreezeMode.Right };
        Assert.True(col.IsFrozenRight);
    }

    // ── EditorItemsString ─────────────────────────────────────────

    [Fact]
    public void EditorItemsString_Set_PopulatesEditorItems()
    {
        var col = new DataGridColumn();
        col.EditorItemsString = "Alpha,Beta,Gamma";
        var items = col.EditorItems!.Cast<string>().ToList();
        Assert.Equal(3, items.Count);
        Assert.Contains("Alpha", items);
        Assert.Contains("Beta", items);
        Assert.Contains("Gamma", items);
    }

    [Fact]
    public void EditorItemsString_TrimsWhitespace()
    {
        var col = new DataGridColumn();
        col.EditorItemsString = " Alpha , Beta , Gamma ";
        var items = col.EditorItems!.Cast<string>().ToList();
        Assert.Contains("Alpha", items);
        Assert.Contains("Beta", items);
        Assert.Contains("Gamma", items);
    }

    [Fact]
    public void EditorItemsString_Empty_DoesNotPopulateEditorItems()
    {
        var col = new DataGridColumn();
        col.EditorItemsString = "";
        // Empty string should not override EditorItems
        Assert.Null(col.EditorItems);
    }

    [Fact]
    public void EditorItemsString_Null_DoesNotPopulateEditorItems()
    {
        var col = new DataGridColumn();
        col.EditorItemsString = null;
        Assert.Null(col.EditorItems);
    }

    [Fact]
    public void EditorItemsString_Get_ReturnsSetValue()
    {
        var col = new DataGridColumn();
        col.EditorItemsString = "A,B,C";
        Assert.Equal("A,B,C", col.EditorItemsString);
    }

    [Fact]
    public void EditorItemsString_RemovesEmptyEntries()
    {
        var col = new DataGridColumn();
        col.EditorItemsString = "A,,B,,,C";
        var items = col.EditorItems!.Cast<string>().ToList();
        Assert.Equal(3, items.Count);
    }

    // ── EditTriggers ──────────────────────────────────────────────

    [Fact]
    public void EditTriggers_Default_IsNull()
    {
        var col = new DataGridColumn();
        Assert.Null(col.EditTriggers);
    }

    [Fact]
    public void EditTriggers_SetToNone_StoresNone()
    {
        var col = new DataGridColumn();
        col.EditTriggers = KumikoUI.Core.Editing.EditTrigger.None;
        Assert.Equal(KumikoUI.Core.Editing.EditTrigger.None, col.EditTriggers);
    }

    [Fact]
    public void EditTriggers_SetToSingleTap_StoresSingleTap()
    {
        var col = new DataGridColumn();
        col.EditTriggers = KumikoUI.Core.Editing.EditTrigger.SingleTap;
        Assert.Equal(KumikoUI.Core.Editing.EditTrigger.SingleTap, col.EditTriggers);
    }

    [Fact]
    public void EditTriggers_SetToCombinedFlags_StoresCombinedFlags()
    {
        var col = new DataGridColumn();
        col.EditTriggers = KumikoUI.Core.Editing.EditTrigger.DoubleTap | KumikoUI.Core.Editing.EditTrigger.F2Key;
        Assert.Equal(
            KumikoUI.Core.Editing.EditTrigger.DoubleTap | KumikoUI.Core.Editing.EditTrigger.F2Key,
            col.EditTriggers);
    }

    [Fact]
    public void EditTriggers_SetThenClearedToNull_IsNull()
    {
        var col = new DataGridColumn { EditTriggers = KumikoUI.Core.Editing.EditTrigger.SingleTap };
        col.EditTriggers = null;
        Assert.Null(col.EditTriggers);
    }

    [Fact]
    public void EditTriggers_TwoColumns_IndependentValues()
    {
        var col1 = new DataGridColumn { EditTriggers = KumikoUI.Core.Editing.EditTrigger.SingleTap };
        var col2 = new DataGridColumn { EditTriggers = KumikoUI.Core.Editing.EditTrigger.None };
        Assert.Equal(KumikoUI.Core.Editing.EditTrigger.SingleTap, col1.EditTriggers);
        Assert.Equal(KumikoUI.Core.Editing.EditTrigger.None, col2.EditTriggers);
    }
}

